#
# Warning: current configuration supports VirtualService traffic only within the same namespace.
# Traffic to service.namespace.svc(.cluster.local) URLs will not be routed by Istio.
#
---
version: v1beta1
export:
  - apiVersion: networking.istio.io/v1beta1
    kind: Gateway

  - apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    patches:
      - op: rewriteName
        path: .spec.gateways[*]
        regex: "($NAMESPACE/)?$NAME"
        conditions:
          - notEqual: "mesh"

  - apiVersion: networking.istio.io/v1beta1
    kind: DestinationRule
    patches:
      - op: rewriteName
        path: .spec.exportTo
        regex: $NAMESPACE
        conditions:
          - notEqual: "."
import:
  - kind: Secret
    apiVersion: v1